### ISSUE TITLE
[rdf2hdt] It's practically impossible to parse large RDF files

### ISSUE THREAD

**Issue by sharpaper** [rdfhdt/hdt-cpp#119] opened 2017-10-27 07:07 UTC
I'm trying to convert a large RDF graph (Turtle, 150GB) to HDT, using `rdf2hdt`. It looks like `rdf2hdt` tries to load **the entire graph** into RAM, and then when it runs out of RAM it starts swapping. To all practical purposes... it's pretty much impossible to generate the `.hdt` file unless I buy 100s and 100s of GB of RAM.
I wonder why you guys decided  to take this decision, that is to load everything into RAM? Wouldn't it be possible to just process the input file in chunks, and update the `.hdt` output file accordingly?

On your website you offer `wikidata.hdt` (the link is broken btw, it returns 404), so I wonder how you were able to create it since the original database is approximately 200GB??

**Comment by akuckartz** [comment] 2017-10-27 07:25
:+1: I also only got 64GB on my relevant computer.

**Comment by sharpaper** [comment] 2017-10-27 07:39
Addendum: I'd also like to note that HDT is most useful with large and very-large graphs. Small graphs (a few GBs) I can already load them into RAM as well as share online without problems. So, if I can't make HDT work with large graphs, then it's pretty much a useless tool.

**Comment by mielvds** [comment] 2017-10-27 08:15
@sharpaper HDT was and still is research POC software. Despite that, it has proven itself to be very useful, especially for the [Linked Data Fragments](linkeddatafragments.org) initiative that runs the complete [DBpedia](fragments.dbpedia.org) with it. But yes, we mostly generate HDT's using [150GB+ RAM](http://lod-a-lot.lod.labs.vu.nl/about/docs/lod-a-lot.pdf), because HDT compresses and indexes aggressively and thus needs a complete overview of the graph. There is no such thing as free compression unfortunately. 

There are already [efforts](https://github.com/rdfhdt/hdt-mr) that improve the memory consumption, but, again, these still need a lot of time, effort and research. For the time being, we are already happy HDT exists in the first place. I'm sorry to hear HDT isn't useful for you, but you only have yourself to blame: everything is described in the papers, the repository is open for pull requests, and we are very happy to answer questions :)

**Comment by sharpaper** [comment] 2017-10-27 08:48
I do believe HDT is an extremely useful tool/project, but unfortunately it's very impractical for larger graphs. And for even larger graphs, it's impossible to use.
Is there any strategy that can be used to handle a graph of arbitrary size, without having to look at the entire graph at once? Something like like this:

1. create an empty `.hdt` file
2. read 1K triples from input `.nt` file
3. update `.hdt` file with new triples
4. repeat 3.

Or maybe split a huge graph into "smaller graphs" like this

```
             query
               |
               |
+-------------------------------+
|      wikidata.hdt (index)     |
+-------------------------------+
           /         \
          /           \
         /             \
+------------+     +------------+
| wiki-1.hdt | ... | wiki-n.hdt |
+------------+     +------------+
```

**Comment by mielvds** [comment] 2017-10-27 09:03
@webdata will have to answer this. I believe he was already looking into a merging strategy for HDT

**Comment by joernhees** [comment] 2017-10-27 20:16
@webdata actually maybe with the pre-sort pipeline this could be solved as well?

**Comment by sharpaper** [comment] 2017-11-03 12:56
[Link](https://phabricator.wikimedia.org/T179681) to relevant thread on WikiData mailing list.

**Comment by lucaswerkmeister** [comment] 2017-11-03 13:17
The README seems to suggest that you can “generat[e] big RDF datasets on machines without much RAM memory” by building with `./configure --with-kyoto=yes`. But I had no success in converting the Wikidata dump with such a build, and then I found #21, which was closed with only the comment

> Kyoto support was never fully completed, unfortunately.

I’m not sure what to make of that – does that mean that Kyoto support isn’t functional, and there are no plans to complete it (otherwise there would be an open issue for it)? And in that case, shouldn’t it be removed from the README?

**Comment by LaurensRietveld** [comment] 2018-03-07 14:44
Good point, just removed the kyoto reference from the readme. It indeed was never functional, and there are no plans on completing it. 
W.r.t. memory usage: as others have said, there is indeed an ongoing effort to improve the memory load. Closing this issue for now though, as it's a bit too broad to act on directly

**Closed by LaurensRietveld** 2018-03-07 14:44 UTC
Labels: enhancement

**Comment by firmao** [comment] 2019-08-07 21:59
Hi, I think the problem is solved in:
Diefenbach, Dennis, and Josée M. Giménez-García. "HDTCat: let's make HDT scale." arXiv preprint arXiv:1809.06859 (2018).
paper: https://arxiv.org/pdf/1809.06859.pdf
