### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by ckrempe** [rdfhdt/hdt-cpp#144] opened 2017-12-22 13:11 UTC
Tryying to compile the last version on Debian wheezy I get the following compiler error:

make[2]: Verzeichnis „/usr/local/hdt-cpp-develop/libhdt“ wird betreten
  CXX      src/bitsequence/libhdt_la-BitSequence375.lo
  CXX      src/dictionary/libhdt_la-KyotoDictionary.lo
In file included from src/bitsequence/BitSequence375.cpp:30:0:
src/bitsequence/../util/bitutil.h: In function ‘bool hdt::bitget(uint32_t*, size_t)’:
src/bitsequence/../util/bitutil.h:86:13: error: redefinition of ‘bool hdt::bitget(uint32_t*, size_t)’
 inline bool bitget(uint32_t *e, size_t p) {
             ^
src/bitsequence/../util/bitutil.h:69:13: note: ‘bool hdt::bitget(size_t*, size_t)’ previously defined here
 inline bool bitget(size_t *e, size_t p) {
             ^
src/bitsequence/../util/bitutil.h: In function ‘void hdt::bitset(uint32_t*, size_t)’:
src/bitsequence/../util/bitutil.h:91:13: error: redefinition of ‘void hdt::bitset(uint32_t*, size_t)’
 inline void bitset(uint32_t * e, size_t p) {
             ^
src/bitsequence/../util/bitutil.h:74:13: note: ‘void hdt::bitset(size_t*, size_t)’ previously defined here
 inline void bitset(size_t * e, size_t p) {
             ^
src/bitsequence/../util/bitutil.h: In function ‘void hdt::bitclean(uint32_t*, size_t)’:
src/bitsequence/../util/bitutil.h:96:13: error: redefinition of ‘void hdt::bitclean(uint32_t*, size_t)’
 inline void bitclean(uint32_t * e, size_t p) {
             ^
src/bitsequence/../util/bitutil.h:79:13: note: ‘void hdt::bitclean(size_t*, size_t)’ previously defined here
 inline void bitclean(size_t * e, size_t p) { ...

Any idea?

**Comment by wouterbeek** [comment] 2017-12-22 13:22
Can you give the numbers for `sizeof(size_t)` and `sizeof(uint32_t)`?

**Comment by ptorrestr** [comment] 2017-12-22 13:23
Hi, Is your system 32-bits architecture? This happens when `sizeof(size_t)` is 32

**Comment by ckrempe** [comment] 2017-12-22 13:26
Yes, 32bit.

**Comment by wouterbeek** [comment] 2017-12-22 13:29
As @ptorrestr indicated, this is a duplicate of https://github.com/rdfhdt/hdt-cpp/issues/143

**Comment by ptorrestr** [comment] 2017-12-22 13:29
As a solution, you just can comment out one of conflicting functions. However, I'm afraid you won't be able to read a `hdt` file created by a 64-bit system.

**Comment by ptorrestr** [comment] 2017-12-22 13:36
@wouterbeek, I think the use of `size_t` for the definition of the hdt binary format would create `hdt` files architecture-dependant, which does not seems to be a good idea for compatibility and interchangeability of `hdt` files. Right now is not possible to read a 64-bit-produced hdt file in a 32-bit system.

**Comment by ckrempe** [comment] 2017-12-22 13:37
stdlib.h says "typedef unsigned int size_t;"
Ok, so I will switch to a 64bit system.

Thanks!

**Closed** 2017-12-22 14:17 UTC
