### ISSUE TITLE
[rdf2hdt] Missing option to generate .hdt.index only

### ISSUE THREAD

**Issue by sharpaper** [rdfhdt/hdt-cpp#121] opened 2017-10-28 07:31 UTC
As far as I can tell, `rdf2hdt` has the flag `-i` to create **both** the `.hdt` file and its `.hdt.index`, but it's lacking an option to create **only** the `.hdt.index` file from a `.hdt`.

**Comment by LaurensRietveld** [comment] 2017-10-28 09:43
It's not really `rdf2hdt` if you already an hdt file ;). This is usually done is by running `hdtSearch -q 0` on an HDT file (or by issuing a regular query). This could be added to the documentation though

**Comment by sharpaper** [comment] 2017-10-29 10:11
Thank you @LaurensRietveld it worked for me! Still failing however for large graphs with `ERROR: std::bad_alloc`.

Any idea how much memory this should require for example, to create the index of wikidata.hdt which is ~23GB?

**Comment by LaurensRietveld** [comment] 2017-10-30 07:30
The documentation issue is fixed by #128. About the memory usage, don't have any stats on that tbh. It greatly depends on the structure of the graph. Perhaps others (e.g. @fernandez ) can pitch in here: is there a paper out there that evaluated the memory use of creating the index file? 

ps. closing this issue in the meantime as the original issue is fixed. Don't let that stop you from discussing the memory usage though

**Closed by LaurensRietveld** 2017-10-30 07:30 UTC
Labels: documentation

**Comment by fernandez** [comment] 2017-11-07 00:25
Hello @LaurensRietveld, and sorry for the delay in commenting here. I'm not involved in this project, so it may be that you are looking for a different user instead.

**Comment by rubensworks** [comment] 2017-11-07 00:31
It was probably @webdata who was intended to be mentioned.
