### ISSUE TITLE
Problems (with escaped quotes?) in Turtle input

### ISSUE THREAD

**Issue by AxelPolleres** [rdfhdt/hdt-cpp#165] opened 2018-03-22 03:51 UTC
Hi HDTers,

the following Turtle (an output of easyrdf's Turtle serializer [1]) is not swallowed by HDT (more concretely by rdf2hdt). I have tested the turtle with other parsers such as rapper [2] which didn't complain. The problem seems to be in the skos:note object and I assume the escaped quotes confuse HDT's parser... any help welcome where to start looking!

Axel
 
1. http://www.easyrdf.org/
2. http://librdf.org/raptor/

```ttl
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix dc: <http://purl.org/dc/terms/> .
@prefix bibo: <http://purl.org/ontology/bibo/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ns0: <http://n2t.net/ark:/99152/p0v#> .
@prefix ns1: <http://www.w3.org/2006/time#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix void: <http://rdfs.org/ns/void#> .

<http://n2t.net/ark:/99152/p044mt93nd6>
  skos:inScheme <http://n2t.net/ark:/99152/p044mt9> ;
  a skos:Concept ;
  dc:language "fra-latn"^^xsd:string ;
  dc:source [
    dc:isPartOf <http://www.worldcat.org/oclc/257445695> ;
    bibo:locator "viii"^^xsd:string
  ] ;
  dc:spatial <http://dbpedia.org/resource/Italy>, <http://dbpedia.org/resource/Greece> ;
  skos:altLabel "The Second Period"@eng-latn, "The Fine Style"@eng-latn, "La seconde époque"@fra-latn ;
  skos:editorialNote """"The Fine Style" alternate label from Birch 1858, 222 (citing Millingen 1813, viii).

Earliest and Latest Stop ISO values inferred from modern chronology of Second Punic War (cf. https://en.wikipedia.org/wiki/Second_Punic_War#cite_ref-1)."""^^xsd:string ;
  skos:note """"La seconde [époque] commençnt ?|  l'année 450, temps où ont fleuri Polygnote [cf. n. 7] et Phidias, est celle où l'Art a atteint son  
plus haut dégré de perfecc
tion [cf. n. 8] elle finiroit quant ?|  l'Italie et ?|  la Sicile, vers la seconde guerre Punique."

[Millingen 1813, viii n. 7]: "'Polygnote, qui florissoit dans la LXXXIIIème Olympiade (444. ans avant notre ére) fut le premier qui peignit des femmes aa
vec des vêtemens transparee ens, des coëffures de différentes couleurs et qui contribua le premier ?|  la perfection de l'Art, car il établit l'usage  
d'ouvrir la bouche aux figures, de faire voir les dents,    de changer l'ancienne roideur des attitudes, Plin. Hist. Nat. lib. XXXV. cap. 9.'"

[Millingen 1813, viii, n. 8]: "L'Art paroit n'être parvenu ?|  sa perfection que du temps de Polygnote et de Phidias. Il est probable que sa marche n'?|  
 pas été tout ?|  fait grr
aduelle, mais qu'il prit un essor sous ces grands artistes, comme celui que Raphaël fit prendre ?|  l'art moderne.""""^^xsd:string ;
  skos:prefLabel "La seconde époque"^^xsd:string ;
  ns1:intervalFinishedBy [
    skos:prefLabel "vers la seconde guerre Punique"^^xsd:string ;
    ns1:hasDateTimeDescription [
      ns0:earliestYear "-0217"^^xsd:gYear ;
      ns0:latestYear "-0200"^^xsd:gYear
    ]
  ] ;
  ns1:intervalStartedBy [
    skos:prefLabel "?|  l'année 450"^^xsd:string ;
    ns1:hasDateTimeDescription [ ns1:year "-0449"^^xsd:gYear ]
  ] .
```

**Comment by AxelPolleres** [comment] 2018-03-22 16:12
Sure, I can also file this to easyrdf as an issue, but would like to make cleear that this is not "my snippet" but something that another software spit out and that again other software consumes (raptor), so maybe we could make HDT robust against this kind of errors without choking? ... In that sense, can we leave the issue open for the moment?

**Comment by sebneu** [comment] 2018-03-22 16:27
The issue here is that a single quoted part starts directly after the triple quotes. I don't know the correct syntax here..? Should single `"`  be allowed at any place in a multi-line literal?
The only rule I found in the definition is: Literals delimited by """ may not contain the sequence of characters """. (https://www.w3.org/TR/turtle/#literals)

**Comment by wouterbeek** [comment] 2018-03-22 19:23
Looking into this a little bit more, there is exactly one invalid character in the posted snippet: it is the last double quote character of the literal that starts and ends with four consecutive double quotes.  The other literal -- i.e., the one that starts with four double quotes and ends with three double quotes -- is valid, because the last double quote of the opening sequence is part of the lexical form (as pointed out by @sebneu, one or two consecutive double quotes are allowed in triple quoted literals, but only in some locations).

In the literal that starts and ends with four consecutive double quotes, the fourth double quote in the closing sequence is the one that violates the Turtle standard.  The first three double quotes mark the end of the lexical form.  Lexical forms must be followed by `^^` (for typed literals), or `@` (for language-tagged strings), or white space and/or punctuation (for abbreviated XSD string notation).  However, lexical forms are not allowed to be followed by a double quote (as is the case in the snippet).  The grammar line that dictates this is [25]:

```
[25] | STRING_LITERAL_LONG_QUOTE | ::= | '"""' (('"' \| '""')? ([^"\] \| ECHAR \| UCHAR))* '"""'
-- | -- | -- | --
```

**Comment by AxelPolleres** [comment] 2018-03-22 19:50
yup, thanks...
seems this is the gist:
---------
@prefix : <http://www.example.org/> .
  
# That fine:
:s :p """"foo" bar""" .

# That isn't (gives me a parse error where I think it shouldn't):
:s :p """"alice" bob "charly"""" .
-------
I think this invalid output comes either from easyrdf.org's json-ld parser or from the source file not being valid JSON)-LD) will see whether I can file the issue there, and look into the source of the problem before... FYI, the source file came from here: https://test.perio.do/#p/ ... I think for around here the issue can be closed without further action. In fact I re-checked with rapper again, it also gives an error there, with the difference that rapper still spits out the triples parses thus far *until* the parser error, which had originally confused me.

**Comment by wouterbeek** [comment] 2018-03-22 19:52
@AxelPolleres Your issue may be solved if easyrdf could be instructed to use single quotes for triple quoted literal notation.  Do you believe that this is possible?  E.g., the offending literal would look similar to the following (which is legal Turtle):

```
'''"text"'''
```

I cannot reproduce your observation WRT Rapper.  Specifically, I get the following (using version 2.0.15):

```
$ rapper snippet.ttl -i turtle > /dev/null 
rapper: Parsing URI file:///home/wbeek/tmp/snippet.ttl with parser turtle
rapper: Serializing with serializer ntriples
rapper: Error - URI file:///home/wbeek/tmp/snippet.ttl:36 - syntax error at '"'
rapper: Failed to parse file snippet.ttl turtle content
rapper: Parsing returned 13 triples
```

As a founding member of the Pedantic Web Group, you will of course agree that we should never purposefully parse syntactically incorrect data.  (After all, being very strict about whether a double quote is allowed at a particular place is The Pedantic Way.)  However, I read your remark as a suggestion to parse correct RDF statements and skip incorrect expressions.  In fact I made such a suggestion along those lines myself in #117, but at the time there was not broad support for this idea.

Serd already has a "lax mode" that allows it to skip those parts of an input stream that it cannot parse, so this lax mode only needs to be configurable from within the HDT API.

**Comment by AxelPolleres** [comment] 2018-03-22 19:53
"As a founding member of the Pedantic Web Group" .... mea culpa ;-)

**Comment by AxelPolleres** [comment] 2018-03-22 20:45
moved to easyRDF's issues list: https://github.com/njh/easyrdf/issues/296

**Closed** 2018-05-07 21:44 UTC
